### PR TITLE
UNLOCK TUNNEL FILES

### PR DESCRIPTION
**Pull request by Bcoderx6**
USE TO UNLOCK ANY TUNNEL FILES

### CODE REVIEW

**Comment by Maxdha** [comment]
People like you are the reason this project isn't maintained anymore.
Idiot.

**Comment by Maxdha** [comment]
Plain stupid.

**Comment by Bcoderx6** [comment]
FUCK U

**Comment by Bcoderx6** [comment]
EXTREAMLY SORRY FOT IT I WII MAKE MY MISTAKES SORRY

**Pull request closed without merging**
